name: Run Cypress Partner Admin Tests
on:
  workflow_run:
    workflows: ['Build and Deploy']
    types:
      - completed

jobs:
  cypress-run:
    name: Run Cypress Partner Admin Tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, edge]
        containers: [1, 2]
    env:
      # ... keep the existing environment variables here ...
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          build: npm ci && npm run build
          start: npm run dev
          wait-on: ${{ env.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
          record: true
          parallel: true
          spec: 'cypress/e2e/partner-admin/default-tests/**/*'
          ci-build-id: ${{ github.run_id }}-${{ matrix.browser }}
