name: Preview Deploy
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ci-preview-tests-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  deployments: write
  pull-requests: write

jobs:
  build-and-preview:
    name: Deploy Preview
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Build (ROAR)
        if: ${{ contains(github.repository, 'roar') }}
        run: npm ci && npm run build
      - name: Build (LEVANTE)
        if: ${{ contains(github.repository, 'levante') }}
        run: npm ci && npm run build:levante-dev
      - name: Deploy to Firebase Hosting Channel
        id: firebase-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseToolsVersion: v13.3.1 # <- Locking version because the newest (13.13.0) does not add the deploy URL to auth whitelist
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV_ADMIN }}'
          projectId: '${{ secrets.FIREBASE_PROJECT }}'
          target: production
      - run: echo ${{ fromJson(steps.firebase-deploy.outputs.urls)[0] }}
    outputs:
      deployUrl: ${{ fromJson(steps.firebase-deploy.outputs.urls)[0] }}
